<?php

namespace WPAIToolbox;

use OpenAI\Exceptions\ErrorException;

class Summarize {
    use Singleton;

    public function generate($request) {

        //summaries can only be generated by people who can edit posts
        if (!current_user_can('edit_posts')) {
            return new \WP_Error('rest_forbidden', esc_html__('You do not have permission to do this.', 'wp-ai-toolbox'), ['status' => 401]);
        }

        $audience = $request->get_param('audience');
        $content = $request->get_param('content');
        $length = $request->get_param('length');

        $summary = wp_kses_post($this->get_summary($audience, $content, $length));

        if($summary instanceof \WP_Error) {
            return new \WP_REST_Response($summary, 500);
        }

        return rest_ensure_response([
            'summary' => $summary,
        ]);
    }

    public function get_summary($audience, $content, $length = 100) {
        $client = OpenAI::instance()->get_client();
        $content = strip_tags($content);
        $prompt = "write a $length word long summary of the following for an audience of $audience: $content";

        try {
            $response = $client->completions()->create([
                'prompt' => json_encode($prompt, JSON_UNESCAPED_SLASHES),
                'model' => 'text-davinci-003',
                'max_tokens' => 2000,
                'temperature' => 0.7,
                'top_p' => 1
            ]);

            return $response->choices[0]->text;
        } catch (ErrorException $e) {
            return new \WP_Error('openai_error', $e->getErrorMessage(), ['status' => 500]);
        }

    }
}